{
 "title": "Odoo / metrics",
 "tags": [ "odoo-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "deployment_name",
    "label": "Deployment name",
    "query": {
     "query": "label_values(odoo_deployment_info,service_namespace)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment environment",
    "query": {
     "query": "label_values(odoo_deployment_info{service_namespace=\"$deployment_name\"},deployment_environment)"
    }
   },
   {
    "name": "deployment_version",
    "label": "Deployment version",
    "query": {
     "query": "label_values(odoo_deployment_info{service_namespace=\"$deployment_name\", deployment_environment=\"$deployment_environment\"},service_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(service_namespace, deployment_environment, service_version) (odoo_deployment_info{service_namespace=\"$deployment_name\", deployment_environment=\"$deployment_environment\", service_version=\"$deployment_version\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(service_namespace, deployment_environment, service_version) (odoo_deployment_info{service_namespace=\"$deployment_name\", deployment_environment=\"$deployment_environment\", service_version=\"$deployment_version\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Request number by path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(request_path) (increase(odoo_requests_total{service_namespace=\"$deployment_name\", deployment_environment=\"$deployment_environment\", service_version=\"$deployment_version\"}[$__range])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate by HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by(service_namespace, deployment_environment, service_version, response_status) (rate(odoo_requests_total{service_namespace=\"$deployment_name\", deployment_environment=\"$deployment_environment\", service_version=\"$deployment_version\"}[$__rate_interval])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(service_namespace,deployment_environment,service_version) (odoo_query_time{service_namespace=\"$deployment_name\",deployment_environment=\"$deployment_environment\",service_version=\"$deployment_version\"})",
     "legendFormat": "Query time"
    },
    {
     "expr": "avg by(service_namespace,deployment_environment,service_version) (odoo_remaining_time{service_namespace=\"$deployment_name\",deployment_environment=\"$deployment_environment\",service_version=\"$deployment_version\"})",
     "legendFormat": "Remaining time"
    },
    {
     "expr": "avg by(service_namespace,deployment_environment,service_version) (odoo_query_count{service_namespace=\"$deployment_name\",deployment_environment=\"$deployment_environment\",service_version=\"$deployment_version\"})",
     "legendFormat": "Query count"
    },
    { "expression": "$A+$B", "type": "math" }
   ]
  }
 ]
}