{
 "title": "Odoo / logs",
 "tags": [ "odoo-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "deployment_name",
    "label": "Deployment name",
    "query": {}
   },
   {
    "name": "deployment_environment",
    "label": "Deployment environment",
    "query": {}
   },
   { "name": "regex_search", "label": "Regex search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=~\"odoo\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=~\"odoo\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"level\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service_name=\"odoo\",service_namespace=~\"$deployment_name\",deployment_environment=~\"$deployment_environment\"}\n|~ \"$regex_search\"\n| label_format timestamp=\"{{__timestamp__}}\",level=detected_level\n[$__interval]))\n",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"odoo\",service_namespace=~\"$deployment_name\",deployment_environment=~\"$deployment_environment\"}\n|~ \"$regex_search\"\n| label_format timestamp=\"{{__timestamp__}}\",level=detected_level\n| line_format `{{ if eq \"[[deployment_name]]\" \".*\" }}{{alignLeft 15 .service_namespace}}|{{end}}{{ if eq \"[[deployment_environment]]\" \".*\" }}{{alignLeft 15 .deployment_environment}}|{{end}}{{alignLeft 5 .service_version}}| {{__line__}}`\n\n"
    }
   ]
  }
 ]
}